language: node_js
node_js:
  - "10"
  - "8"
  - "6"
  - "4"
notifications:
  email:
    recipients:
      - shaojinhong@kuaizi.co
    on_success: always # default: change
    on_failure: never # default: always